services:

  nginx:
    container_name: nginx
    build: ./srcs/nginx
    ports:
    - "443:443"
    networks:
    - inception-network

  wordpress:
    container_name: wordpress
    build: ./srcs/wordpress
    networks:
    - inception-network
    ports:
    - "9000"

  # mariadb:
  #   container_name: mariadb
  #   build: ./srcs/mariaDB
  #   networks:
  #   - inception-network
  #   ports:
  #   - "3306"

networks:
  inception-network:
    driver: bridge