version: '3'

# SERVICES
# This section defines the services that will be started.
# Docker will create a container for each service using the
# image specified in the build section (Dockerfile).
services:
  nginx:
      container_name: nginx
      build: ./srcs/nginx
      ports:
         - 443:443
      volumes:
        - wordpress_data:/var/www/html
      restart: always
      networks:
        - network

  mariadb:
    container_name: mariadb
    build: ./srcs/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./srcs/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

# VOLUMES
# Volumes are used to persist data between container restarts.
# Data is stored on the host machine in the specified directory.

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/nroth/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/nroth/data/wordpress
      o: bind

# NETWORKS
# Networks are used to connect containers together.
# They work in a similar way to a physical network (like  virtual switch).
networks:
  network:
    driver: bridge
