version: '3'

services:
  nginx:
    container_name: nginx
    build: ./srcs/nginx
    ports:
        - 443:443
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception_network

  mariadb:
    container_name: mariadb
    build: ./srcs/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: always
    env_file:
      - .env
    healthcheck:
      test: find healthcheck.txt
      interval: 2s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s


  wordpress:
    container_name: wordpress
    build:
      context: ./srcs/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: find wp-config.php
      interval: 2s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

# volumes are stored on the host machine, and are mounted into the
## containers in a specified directory.
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/nroth/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/nroth/data/wordpress
      o: bind

#the network connecting the containers.
networks:
  inception_network:
    driver: bridge
