services:

  nginx:
    container_name: nginx
    build: ./srcs/nginx
    ports:
    - "443:443"
    networks:
    - inception-network

  mariadb:
    container_name: mariadb
    build: ./srcs/mariadb
    networks:
    - inception-network
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./srcs/wordpress
    networks:
    - inception-network
    env_file:
      - .env


networks:
  inception-network:
    driver: bridge